//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuBaoHanh
    {
        public string MaPBH { get; set; }
        public Nullable<System.DateTime> NgayGuiBH { get; set; }
        public Nullable<System.DateTime> NgayTraBH { get; set; }
        public string LyDoBH { get; set; }
        public string TinhTrangSP { get; set; }
        public Nullable<decimal> ChiPhiBH { get; set; }
        public string MaSPBH { get; set; }
        public string MaHD { get; set; }
        public string MaNV { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
