//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuatKho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuXuatKho()
        {
            this.ChiTietPXKs = new HashSet<ChiTietPXK>();
        }
    
        public string MaPXK { get; set; }
        public Nullable<System.DateTime> NgayXuatKho { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public string MaKho { get; set; }
        public string MaNV { get; set; }
        public string MaHD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPXK> ChiTietPXKs { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual Kho Kho { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
